=== Arpanakumal/github-demo/arpanaxml/13/13.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
        <xs:complexType name="nameType">
            <xs:sequence>
                <xs:element name="fname" type="xs:string"></xs:element>
                <xs:element name="mname" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="lname" type="xs:string"></xs:element>
           </xs:sequence>
         </xs:complexType>
        <xs:complexType name="diseaseType">
            <xs:sequence>
                <xs:element name="name1" type="xs:string"></xs:element>
                <xs:element name="name2" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="labTestType">
            <xs:sequence>
                <xs:element name="lab1" type="xs:string"></xs:element>
                <xs:element name="lab2" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="doctor">
            <xs:sequence>
                <xs:element name="fname" type="xs:string"></xs:element>
                <xs:element name="mname" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="lname" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:element name="patient">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="name" type="xs:string"></xs:element>
                    <xs:element name="disease" type="xs:string"></xs:element>
                    <xs:element name="doctor" type="xs:string"></xs:element>
                </xs:sequence>
                <xs:attribute name="no" type="xs:int"></xs:attribute>
                <xs:attribute name="charge" type="xs:int"></xs:attribute>
            </xs:complexType>
        </xs:element>
        <xs:element name="patients">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="patient" type="xs:anyType" minOccurs="0" maxOccurs="unbounded"></xs:element> 
            </xs:sequence>
            </xs:complexType>
    
            
        </xs:element>




</xs:schema>

=== Arpanakumal/github-demo/arpanaxml/13/13.xml
<?xml version="1.0" encoding="UTF-8"?>
<patients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="13.xsd">

<patient no="00125">
    <name>
    <fname>Shruti</fname>
    <mname>Kumari</mname>
    <lname>Lama</lname>
</name>
    <disease>
        <name>
        <name1>Obesity</name1>
        <name2>Diabetes  </name2>
    </name>
    </disease>
    <labTest>
        <lab1>Blood sample</lab1>
        <lab2>Urine sample</lab2>
    </labTest>

    <doctor>
        <namne>
            <fname>Suman</fname>
            <mname>Jung</mname>
            <lname>Karki</lname>
        </namne> 
    </doctor>
        <consultation charge="5500"></consultation>

</patient>
</patients>
